/* Autogenerated by png2wx.pl on Mon May  4 16:35:57 2015 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_Polar;

#endif /* ICONS_H */
